frequency: 30
sensor_timeout: 0.1
two_d_mode: false
transform_time_offset: 0.0
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: /rtabmap/odom
imu0: /mavros/imu/data

odom0_config: [true,  true,  false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]
imu0_config:  [false, false, false,
               true,  true,  true,
               false, false, false,
               true,  true,  true,
               false, false, true]

odom0_queue_size: 10
imu0_queue_size: 10

odom0_nodelay: false
imu0_nodelay: false

odom0_differential: false
imu0_differential: false

odom0_relative: false
imu0_relative: false

imu0_remove_gravitational_acceleration: true
